// src/lib/page-components.ts

export const pageComponentMap: Record<string, string[]> = {
    // --- Main Site ---
    "Página de Inicio": [
        "Header Optimizado",
        "Hero Animado",
        "Sección de Visión y Estadísticas",
        "Resumen de Servicios Principales",
        "Sección de Llamado a la Acción (CTA)",
        "Soluciones para Emprendedores (Home)",
        "Slider de Servicios para Negocios",
        "Carrusel de Redes Sociales",
        "Footer con Botón 'Volver Arriba'",
    ],
    "Envíos Express": [
        "Hero de Envíos Express",
        "Contenido de Envíos Express",
        "Tabla de Precios Express",
        "Beneficios del Servicio Express",
        "Escenarios de Uso Urgente",
        "CTA de Envíos Express",
    ],
    "Envíos LowCost": [
        "Hero de Envíos Low Cost",
        "Contenido de Envíos Low Cost",
        "Comparativa de Precios Low Cost",
        "Beneficios del Servicio Low Cost",
        "Cómo Funciona Low Cost",
        "CTA de Envíos Low Cost",
    ],
    "Moto Fija": [
        "Hero de Moto Fija",
        "Contenido de Moto Fija",
        "Características del Servicio",
        "Clientes Ideales",
        "Planes y Tarifas",
        "CTA de Moto Fija",
    ],
    "Delivery Gastronómico": [
        "Hero de Delivery Gastronómico",
        "Misión Gastronómico",
        "Diferencia del Servicio",
        "Beneficios para el Negocio",
        "Preguntas Frecuentes (Gastronomía)",
        "CTA para Asesoramiento (Gastronomía)",
    ],
    "Plan Emprendedores": [
        "Hero del Plan Emprendedores",
        "Información del Plan",
        "Beneficios para Emprendedores",
        "Tarifas para Emprendedores",
        "CTA del Plan Emprendedores",
    ],
    "Mercado Libre Flex": [
        "Hero de Envíos Flex",
        "Contenido de Envíos Flex",
        "Beneficios de Mercado Libre",
        "Tarifas de Envíos Flex",
        "Cómo Funciona Envíos Flex",
        "Requisitos y Restricciones",
        "CTA de Envíos Flex",
    ],
    "Cotizar Express": [
        "Hero del Cotizador Express",
        "Calculadora Express",
        "Características del Mapa",
        "Información de Precios",
        "Consejos para Cotizar",
        "Contacto para Casos Especiales",
    ],
    "Cotizar LowCost": [
        "Hero del Cotizador Low Cost",
        "Calculadora Low Cost",
        "Características del Mapa",
        "Información de Precios",
        "Consejos para Cotizar",
        "Contacto para Casos Especiales",
    ],
    "Sobre Nosotros": [
        "Hero de Sobre Nosotros",
        "Sección Quiénes Somos",
        "Valores de la Empresa",
        "Historia de la Empresa",
        "Sección del Equipo",
        "Misión y Visión",
    ],
    "Preguntas Frecuentes": [
        "Hero de Preguntas Frecuentes",
        "Categorías de Preguntas",
        "CTA de Contacto para Dudas",
    ],
    "Nuestras Redes": [
        "Hero de Redes Sociales",
        "Conexión a Redes Sociales",
        "Feed de Publicaciones Sociales",
        "Beneficios de Seguirnos",
        "Suscripción a Newsletter",
    ],
    "Contacto": [
        "Hero de Contacto",
        "Información de Contacto",
        "Formulario de Contacto",
        "Horarios de Atención",
        "Mapa de Cobertura",
    ],

    // --- Admin Panel ---
    "Dashboard": [
        "Header de Administración",
        "Panel de Control Principal (Dashboard)",
        "Footer",
    ],
    "Órdenes": [
        "Header de Administración",
        "Tabla de Órdenes",
        "Footer",
    ],
     "Clientes": [
        "Header de Administración",
        "Formulario para Crear Cliente",
        "Tabla de Clientes",
        "Footer",
    ],
    "Repartidores": [
        "Header de Administración",
        "Selector de Repartidor",
        "Hoja de Ruta",
        "Gestión de Repartidores (Modal)",
        "Footer",
    ],
    "Tarifas": [
        "Header de Administración",
        "Pestañas de Tipos de Servicio",
        "Tabla de Precios Editable",
        "Footer",
    ],
    "Etiquetas": [
        "Header de Administración",
        "Barra de Herramientas de Etiquetas",
        "Tabla de Etiquetas",
        "Footer",
    ],
    "Agregar Publicación": [
        "Header de Administración",
        "Formulario para Añadir Post Social",
        "Footer",
    ],
    "Prompts de Imagen": [
        "Header de Administración",
        "Generador de Prompts de Imagen (IA)",
        "Footer",
    ],
    "Generador de Prompts": [
        "Header de Administración",
        "Pestañas (Página/Componente)",
        "Generador de Prompt por Página",
        "Generador de Prompt por Componente",
        "Footer",
    ]
};
