import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--on-primary))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--on-secondary))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--on-error))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--on-surface))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--on-surface))",
        },
        'surface': "hsl(var(--surface))",
        'surface-dim': "hsl(var(--surface-dim))",
        'surface-bright': "hsl(var(--surface-bright))",
        'surface-container-lowest': "hsl(var(--surface-container-lowest))",
        'surface-container-low': "hsl(var(--surface-container-low))",
        'surface-container': "hsl(var(--surface-container))",
        'surface-container-high': "hsl(var(--surface-container-high))",
        'surface-container-highest': "hsl(var(--surface-container-highest))",
        'on-surface': "hsl(var(--on-surface))",
        'on-surface-variant': "hsl(var(--on-surface-variant))",
        'inverse-surface': "hsl(var(--inverse-surface))",
        'inverse-on-surface': "hsl(var(--inverse-on-surface))",
        'outline': "hsl(var(--outline))",
        'outline-variant': "hsl(var(--outline-variant))",
        'surface-tint': "hsl(var(--surface-tint))",
        'primary-container': "hsl(var(--primary-container))",
        'on-primary-container': "hsl(var(--on-primary-container))",
        'inverse-primary': "hsl(var(--inverse-primary))",
        'secondary-container': "hsl(var(--secondary-container))",
        'on-secondary-container': "hsl(var(--on-secondary-container))",
        'tertiary': "hsl(var(--tertiary))",
        'on-tertiary': "hsl(var(--on-tertiary))",
        'tertiary-container': "hsl(var(--tertiary-container))",
        'on-tertiary-container': "hsl(var(--on-tertiary-container))",
        'error': "hsl(var(--error))",
        'on-error': "hsl(var(--on-error))",
        'error-container': "hsl(var(--error-container))",
        'on-error-container': "hsl(var(--on-error-container))",
        'primary-fixed': "hsl(var(--primary-fixed))",
        'primary-fixed-dim': "hsl(var(--primary-fixed-dim))",
        'on-primary-fixed': "hsl(var(--on-primary-fixed))",
        'on-primary-fixed-variant': "hsl(var(--on-primary-fixed-variant))",
        'secondary-fixed': "hsl(var(--secondary-fixed))",
        'secondary-fixed-dim': "hsl(var(--secondary-fixed-dim))",
        'on-secondary-fixed': "hsl(var(--on-secondary-fixed))",
        'on-secondary-fixed-variant': "hsl(var(--on-secondary-fixed-variant))",
        'tertiary-fixed': "hsl(var(--tertiary-fixed))",
        'tertiary-fixed-dim': "hsl(var(--tertiary-fixed-dim))",
        'on-tertiary-fixed': "hsl(var(--on-tertiary-fixed))",
        'on-tertiary-fixed-variant': "hsl(var(--on-tertiary-fixed-variant))",
        'surface-variant': "hsl(var(--surface-variant))",
        'header-blue': "hsl(var(--header-blue))",
        'text-secondary': "hsl(var(--text-secondary))",
        'fab-icon': "hsl(var(--fab-icon))",
        'social-container': "hsla(var(--social-container) / 0.15)",


      },
      spacing: {
        'base': "4px",
        'xs': "4px",
        'sm': "8px",
        'md': "16px",
        'lg': "24px",
        'xl': "32px",
        'gutter': "20px",
        'margin-mobile': "16px",
        'margin-desktop': "40px",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "h-scroll": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "h-scroll": "h-scroll 45s linear infinite",
        float: "float 6s ease-in-out infinite",
        "spin-slow": "spin-slow 8s linear infinite",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        display: ["var(--font-hanken)", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      }},
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config